#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Compile solver
cd applications/
wmake laplacianFoamMuiTest
cd ..

# Run test case
cd tests/
./Allrun-coupling

#------------------------------------------------------------------------------
